Feature 1356
mbrainerd/tk-multi-setframerange pull request #1
Opened 2019-03-06 11:19 UTC by jroy1992

2019-03-07 03:15 UTC, mbrainerd commented on info.yml
> +        default_value: 1001
Please do not define a default value

2019-03-07 03:15 UTC, mbrainerd commented on info.yml
> +        default_value: 1100
Please do not define a default value

2019-03-07 03:17 UTC, mbrainerd commented on app.py
> +        if self.context.entity["type"] == "Asset":
Rather than a hardcoded assumption, this should be a query on the entity type to see if it supports a frame range.

2019-03-07 03:19 UTC, mbrainerd requested changes
Please see inline comments.

2019-03-07 12:57 UTC, jroy1992 commented
Addressed the changes suggested by @mbrainerd.

2019-03-07 18:27 UTC, mbrainerd commented on app.py
> +            if not str(e).startswith("Not supported frame operation '"):
This is ugly. Use a new Exception class.

2019-03-07 18:28 UTC, mbrainerd commented on app.py
> +        return (default_in, default_out)
You need exception handling for when these values aren't set. You should raise an Exception and catch above if necessary.

2019-03-07 18:29 UTC, mbrainerd commented on app.py
> +            if not str(e).startswith("Not supported frame operation '"):
This is ugly. Use a new Exception class.

2019-03-07 18:29 UTC, mbrainerd commented on app.py
> +            raise tank.TankError("Unexpected type returned from 'hook_frame_operation' for operation get_frame_range - expected a 'tuple' with (in_frame, out_frame) values but returned '%s' : %s"
Use a specific Exception class.

2019-03-07 18:31 UTC, mbrainerd commented on app.py
> +            raise tank.TankError("Unexpected type returned from 'hook_frame_operation' for operation get_frame_range - expected a 'tuple' with (in_frame, out_frame) values but returned '%s' : %s"
Also, please stay within 100 spaces

2019-03-07 18:32 UTC, mbrainerd commented on app.py
> +        if sg_in_field not in data or sg_out_field not in data:
You should keep the original exception code

2019-03-07 18:57 UTC, mbrainerd commented on app.py
> +        (status, new_in, new_out) = self.get_frame_range_from_shotgun()
It is more Pythonic to use try/except blocks here:

```python
message = ""
try:
    try:
        (new_in, new_out) = self.get_frame_range_from_shotgun()
    except FrameOperationNotSupported:
        if not self.get_setting("use_default_values"):
            raise
        else:
            message += "{0} and ".format(str(e))
            (new_in, new_out) = self.get_default_frame_range()
except FrameOperationNotSupported, NoDefaultRangeDefined as e:
    message += "{0} {1}".format(str(e), "Not Updating frame range.")
    QtGui.QMessageBox.information(None, "No frame data available!", message)
except Exception as e:
    message += "{0} {1}".format(str(e), "Not Updating frame range.")
    QtGui.QMessageBox.information(None, "Uncaught exception!", message)
```

2019-03-07 18:58 UTC, mbrainerd commented on app.py
> +                msg = "default frame ranges"
"default frame range"

2019-03-07 18:58 UTC, mbrainerd commented on app.py
> +            msg = "latest frame ranges from shotgun"
"latest frame range from shotgun"

2019-03-07 19:05 UTC, mbrainerd requested changes
More inline comments.

2019-03-11 04:26 UTC, jroy1992 commented on app.py
> +            if not str(e).startswith("Not supported frame operation '"):
oh :|
I simply merged Diego's changes focusing more on if it was working or not. Didn't pay much attention on how it was written which clearly was a mistake.
Let me go through it all again and fix it.

2019-03-11 06:34 UTC, jroy1992 commented on app.py
> +        return (default_in, default_out)
If these values are not set, then it will be caught at the time of loading the app. So by the time we reach here, we can safely assume that the values are already set.

Under ___load_apps_ in engine.py:
```
try:
    app_obj = load_application(self, self.context, self.env, app_instance_name)

except TankError as e:
    # validation error - probably some issue with the settings!
    # report this as an error message.
    self.log_error("App configuration Error for %s (configured in environment '%s'). "
                   "It will not be loaded: %s" % (app_instance_name, self.env.disk_location, e))
    continue
```

2019-03-11 23:34 UTC, mbrainerd commented on app.py
> +        return (default_in, default_out)
We shouldn't force the definition of default values in the configuration. You should specify `allows_empty: True` in info.yml and then catch it here.

2019-03-13 12:27 UTC, jroy1992 commented on app.py
> +        return (default_in, default_out)
Looks like we do not have `allows_empty: True` for `int` type settings. Moving it into a `dict` type setting so as to enable `allows_empty: True`.

2019-03-13 12:47 UTC, jroy1992 commented
Addressed the inline comments.

2019-03-13 20:33 UTC, mbrainerd approved these changes
LGTM :)

2019-03-14 05:27 UTC, merged